services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - ckan-aod_default
    env_file:
      - .env
#    environment:
#      - DEBUG=express:*
    ports:
      - "4200:4200"
    volumes:
      - "$SERVER_LOG_PATH:/app/logs"
#    command: tail -f /dev/null
  postgres:
    image: postgres:15
    restart: always
    networks:
      - ckan-aod_default
    environment:
        POSTGRES_USER: $DB_USER
        POSTGRES_PASSWORD: $DB_PASSWORD
        POSTGRES_DB: $DB_NAME
    volumes:
        - "$POSTGRES_DATA_PATH:/var/lib/postgresql/data"

networks:
  ckan-aod_default:
    name: ckan-aod_default
    external: true
